In [1]:
import nfl_data_py as nfl

data = nfl.import_seasonal_data([2023], 'REG')
columns_to_select = ['player_id', 'fantasy_points_ppr', 'ppr_sh']
data_subset = data[columns_to_select]
display(data_subset)

      player_id  fantasy_points_ppr    ppr_sh
0    00-0023459                0.00  0.000000
1    00-0024243               12.90  0.028467
2    00-0026158              100.84  0.191464
3    00-0026498              243.10  0.173299
4    00-0026625                4.94  0.036106
..          ...                 ...       ...
583  00-0039150              156.38  0.154486
584  00-0039152              102.02  0.159821
585  00-0039163              275.02  0.206779
586  00-0039164               72.68  0.213689
587  00-0039165              106.10  0.080979

[588 rows x 3 columns]

In [3]:
display(data)

,player_id,season,season_type,completions,attempts,passing_yards,passing_tds,interceptions,sacks,sack_yards,...,yac_sh,wopr_y,ry_sh,rtd_sh,rfd_sh,rtdfd_sh,dom,w8dom,yptmpa,ppr_sh
0,00-0023459,2023,REG,0,1,0.0,0,0.0,1.0,10.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,00-0024243,2023,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.069712,0.057342,0.027384,0.125,0.036364,0.047619,0.076192,0.046907,0.197279,0.028467
2,00-0026158,2023,REG,123,204,1616.0,13,8.0,8.0,57.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.191464
3,00-0026498,2023,REG,326,521,3965.0,24,11.0,30.0,205.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.173299
4,00-0026625,2023,REG,23,42,231.0,0,2.0,1.0,8.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.036106
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,00-0039150,2023,REG,315,527,2877.0,11,10.0,62.0,477.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.154486
584,00-0039152,2023,REG,149,255,1808.0,8,4.0,28.0,185.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.159821
585,00-0039163,2023,REG,319,499,4108.0,23,5.0,38.0,331.0,...,0.000562,0.002783,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.206779
586,00-0039164,2023,REG,50,84,577.0,3,1.0,7.0,29.0,...,0.000000,0.000000,0.000000,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.213689
587,00-0039165,2023,REG,0,0,0.0,0,0.0,0.0,0.0,...,0.125506,0.100465,0.052938,0.000,0.039326,0.035176,0.026469,0.042351,0.379310,0.080979

In [4]:
print(data.columns)

Index(['player_id', 'season', 'season_type', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr_x', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr',
       'games', 'tgt_sh', 'ay_sh', 'yac_sh', 'wopr_y', 'ry_sh', 'rtd_sh',
       'rfd_sh', 'rtdfd_sh', 'dom', 'w8dom', 'yptmpa', 'ppr_sh'],
      dtype='object')